from setuptools import setup

setup(
    name='decomments_isc',
    version='0.99.2',
    py_modules=['decomments_isc'],
    url='https://github.com/egberts/decommentsisc',
    license='MIT',
    author='segbert',
    author_email='egberts@github.com',
    description='Removes all C-style, C++-style, and Shell/Bash-style comments from a text string',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Intended Audience :: Information Technology',
        'Topic :: Software Development :: Build Tools',
        'Topic :: Internet :: Name Service (DNS)',
        'Topic :: System :: Installation/Setup',
        'Topic :: System :: Systems Administration',
        'Topic :: Text Processing :: Filters',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
)
